### ISSUE TITLE
windowAction's changeWindowSize method gives error: X Error of failed request:  BadDrawable (invalid Pixmap or Window parameter)

### ISSUE THREAD

**Issue by terrsoshi** [RandomGuy-coder/Gestro#11]
The method is giving another error code of which is listed below:
X Error of failed request:  BadDrawable (invalid Pixmap or Window parameter)
  Major opcode of failed request:  14 (X_GetGeometry)
  Resource id in failed request:  0x1
  Serial number of failed request:  11
  Current serial number in output stream:  11

**Comment by MuhatasimIntisar** [comment]
I have added some error handling in there. SO please check again when able

**Comment by terrsoshi** [comment]
Thanks, it is working now!
