### ISSUE TITLE
Callback interface for ubuntu_controls

### ISSUE THREAD

**Issue by RandomGuy-coder** [RandomGuy-coder/Gestro#28]
We need a callback interface for ubuntu_controls, so the coordiantes and finger count can be sent and rest of the processing is hidden.

**Comment by MuhatasimIntisar** [comment]
Only one of the functions is currently working within the callback

**Comment by MuhatasimIntisar** [comment]
I have made changes to the display class and the callback class. Please test to see if now other methods are also being called

**Comment by MuhatasimIntisar** [comment]
Ne version of displaycontrol.cpp added to clarify the issue
