### ISSUE TITLE
windowAction's changeWindowSize gives error code "Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)"

### ISSUE THREAD

**Issue by terrsoshi** [RandomGuy-coder/Gestro#9]

**Comment by terrsoshi** [comment]
Also, I would like to request some information on how do the _windowAction_ **detect the current window** and **implement the functionality on a specific window.**

**Comment by MuhatasimIntisar** [comment]
Please test to see if window control works correctly now.

**Comment by MuhatasimIntisar** [comment]
The window that will be controlled is whichever one is currently in focus either through keyboard or mouse interaction
